import { randomBytes } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { docker } from "~/lib/docker.server";

function wpSalt(): string {
  return randomBytes(32).toString("base64url");
}

/**
 * Run a command inside a container and return its exit code (panel uses Docker API; no TCP to DB from panel).
 */
async function execInContainer(
  containerName: string,
  cmd: string[],
  env: string[] = []
): Promise<number> {
  const container = docker.getContainer(containerName);
  const execInstance = await container.exec({
    Cmd: cmd,
    Env: env,
    AttachStdout: true,
    AttachStderr: true,
    User: "root",
  });

  return new Promise((resolve, reject) => {
    execInstance.start({ hijack: true, Tty: false }, (err, stream) => {
      if (err) {
        reject(err);
        return;
      }
      if (!stream) {
        resolve(-1);
        return;
      }
      stream.resume();
      stream.on("end", () => {
        execInstance.inspect((inspectErr, data) => {
          if (inspectErr) reject(inspectErr);
          else resolve(data?.ExitCode ?? -1);
        });
      });
      stream.on("error", reject);
    });
  });
}

/**
 * Wait until MariaDB in the site DB container accepts connections (via `mysqladmin ping` inside that container).
 * The panel is not on the site's Docker network, so we must not probe `jigsaw_<slug>_db:3306` from the panel process.
 */
export async function waitForMysqlInContainer(
  containerName: string,
  rootPassword: string,
  opts: { timeoutMs?: number; intervalMs?: number } = {}
): Promise<void> {
  const timeoutMs = opts.timeoutMs ?? 120_000;
  const intervalMs = opts.intervalMs ?? 2_000;
  const deadline = Date.now() + timeoutMs;
  const env = [`MYSQL_ROOT_PASSWORD=${rootPassword}`];

  while (Date.now() < deadline) {
    const code = await execInContainer(
      containerName,
      ["sh", "-c", 'mysqladmin ping -h 127.0.0.1 -uroot -p"$MYSQL_ROOT_PASSWORD" 2>/dev/null'],
      env
    );
    if (code === 0) return;
    await new Promise((r) => setTimeout(r, intervalMs));
  }

  throw new Error(
    `Timed out waiting for MariaDB in ${containerName}. Check the database container logs.`
  );
}

function buildWpConfigPhp(params: {
  dbHost: string;
  dbName: string;
  dbUser: string;
  dbPassword: string;
  tablePrefix: string;
}): string {
  const keys = {
    AUTH_KEY: wpSalt(),
    SECURE_AUTH_KEY: wpSalt(),
    LOGGED_IN_KEY: wpSalt(),
    NONCE_KEY: wpSalt(),
    AUTH_SALT: wpSalt(),
    SECURE_AUTH_SALT: wpSalt(),
    LOGGED_IN_SALT: wpSalt(),
    NONCE_SALT: wpSalt(),
  };

  const keyLines = Object.entries(keys)
    .map(([k, v]) => `define('${k}', '${v.replace(/'/g, "\\'")}');`)
    .join("\n");

  return `<?php
/**
 * Generated by Jigsaw — https://github.com/03c/jigsaw
 */
define('DB_NAME', '${params.dbName.replace(/'/g, "\\'")}');
define('DB_USER', '${params.dbUser.replace(/'/g, "\\'")}');
define('DB_PASSWORD', '${params.dbPassword.replace(/'/g, "\\'")}');
define('DB_HOST', '${params.dbHost.replace(/'/g, "\\'")}');
define('DB_CHARSET', 'utf8mb4');
define('DB_COLLATE', '');

${keyLines}

$table_prefix = '${params.tablePrefix.replace(/[^a-z0-9_]/gi, "") || "wp_"}';

define('WP_DEBUG', false);

if (!defined('ABSPATH')) {
    define('ABSPATH', __DIR__ . '/');
}

require_once ABSPATH . 'wp-settings.php';
`;
}

/**
 * Copy WordPress core from the published WordPress image into the site's web root on the Docker host.
 * Uses a one-shot container with dockerode (no `docker` CLI required inside the panel image).
 */
export async function copyWordPressCoreFromImage(params: {
  webImage: string;
  /** Absolute host path, e.g. /home/owner/site/public_html (same path the daemon bind-mounts) */
  hostWebRoot: string;
}): Promise<void> {
  await fs.mkdir(params.hostWebRoot, { recursive: true });

  const container = await docker.createContainer({
    Image: params.webImage,
    Cmd: ["sh", "-c", "cp -a /opt/jigsaw/wordpress-baked/. /out/"],
    HostConfig: {
      Binds: [`${params.hostWebRoot}:/out`],
      AutoRemove: true,
    },
  });

  await container.start();
  const wait = await container.wait();
  if (wait.StatusCode !== 0) {
    throw new Error(
      `WordPress core copy failed (exit ${wait.StatusCode}). Ensure image ${params.webImage} exists on this host.`
    );
  }
}

/**
 * Write wp-config.php after core files are on disk.
 */
export async function writeWordPressConfig(params: {
  panelWebRoot: string;
  dbHost: string;
  dbName: string;
  dbUser: string;
  dbPassword: string;
}): Promise<void> {
  const wpConfig = buildWpConfigPhp({
    dbHost: params.dbHost,
    dbName: params.dbName,
    dbUser: params.dbUser,
    dbPassword: params.dbPassword,
    tablePrefix: "wp_",
  });

  await fs.writeFile(path.join(params.panelWebRoot, "wp-config.php"), wpConfig, "utf-8");
}

/**
 * Tighten wp-config.php permissions inside the web container (avoid world-readable secrets on the host mount).
 */
export async function secureWordPressConfigInWebContainer(webContainerName: string): Promise<void> {
  try {
    const container = docker.getContainer(webContainerName);
    const exec = await container.exec({
      Cmd: [
        "sh",
        "-c",
        "test -f /var/www/html/wp-config.php && chown www-data:www-data /var/www/html/wp-config.php && chmod 640 /var/www/html/wp-config.php",
      ],
      AttachStdout: true,
      AttachStderr: true,
      User: "root",
    });
    await new Promise<void>((resolve, reject) => {
      exec.start({ hijack: true, Tty: false }, (err, stream) => {
        if (err) {
          reject(err);
          return;
        }
        if (!stream) {
          resolve();
          return;
        }
        stream.resume();
        stream.on("end", () => resolve());
        stream.on("error", reject);
      });
    });
  } catch {
    // Best-effort
  }
}
