import { randomBytes } from "node:crypto";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import net from "node:net";
import AdmZip from "adm-zip";

const WORDPRESS_ZIP_URL = "https://wordpress.org/latest.zip";

function wpSalt(): string {
  return randomBytes(32).toString("base64url");
}

/**
 * Wait until MariaDB accepts TCP connections on the given host:port (Docker network).
 */
export async function waitForMysqlHost(
  host: string,
  port: number,
  opts: { timeoutMs?: number; intervalMs?: number } = {}
): Promise<void> {
  const timeoutMs = opts.timeoutMs ?? 120_000;
  const intervalMs = opts.intervalMs ?? 2_000;
  const deadline = Date.now() + timeoutMs;

  while (Date.now() < deadline) {
    const ok = await new Promise<boolean>((resolve) => {
      const socket = net.createConnection({ host, port }, () => {
        socket.end();
        resolve(true);
      });
      socket.on("error", () => resolve(false));
      socket.setTimeout(5_000, () => {
        socket.destroy();
        resolve(false);
      });
    });
    if (ok) return;
    await new Promise((r) => setTimeout(r, intervalMs));
  }

  throw new Error(
    `Timed out waiting for MySQL at ${host}:${port}. Check the database container logs.`
  );
}

function buildWpConfigPhp(params: {
  dbHost: string;
  dbName: string;
  dbUser: string;
  dbPassword: string;
  tablePrefix: string;
}): string {
  const keys = {
    AUTH_KEY: wpSalt(),
    SECURE_AUTH_KEY: wpSalt(),
    LOGGED_IN_KEY: wpSalt(),
    NONCE_KEY: wpSalt(),
    AUTH_SALT: wpSalt(),
    SECURE_AUTH_SALT: wpSalt(),
    LOGGED_IN_SALT: wpSalt(),
    NONCE_SALT: wpSalt(),
  };

  const keyLines = Object.entries(keys)
    .map(([k, v]) => `define('${k}', '${v.replace(/'/g, "\\'")}');`)
    .join("\n");

  return `<?php
/**
 * Generated by Jigsaw — https://github.com/03c/jigsaw
 */
define('DB_NAME', '${params.dbName.replace(/'/g, "\\'")}');
define('DB_USER', '${params.dbUser.replace(/'/g, "\\'")}');
define('DB_PASSWORD', '${params.dbPassword.replace(/'/g, "\\'")}');
define('DB_HOST', '${params.dbHost.replace(/'/g, "\\'")}');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');

${keyLines}

$table_prefix = '${params.tablePrefix.replace(/[^a-z0-9_]/gi, "") || "wp_"}';

define('WP_DEBUG', false);

if (!defined('ABSPATH')) {
    define('ABSPATH', __DIR__ . '/');
}

require_once ABSPATH . 'wp-settings.php';
`;
}

/**
 * Download WordPress, extract into web root, and write wp-config.php (database must be reachable separately).
 */
export async function installWordPressFiles(params: {
  panelWebRoot: string;
  dbHost: string;
  dbName: string;
  dbUser: string;
  dbPassword: string;
}): Promise<void> {
  await fs.mkdir(params.panelWebRoot, { recursive: true });

  const res = await fetch(WORDPRESS_ZIP_URL);
  if (!res.ok) {
    throw new Error(`Failed to download WordPress: HTTP ${res.status}`);
  }

  const buf = Buffer.from(await res.arrayBuffer());
  const zip = new AdmZip(buf);
  const tmp = await fs.mkdtemp(path.join(os.tmpdir(), "jigsaw-wp-"));
  try {
    zip.extractAllTo(tmp, true);
    const extracted = path.join(tmp, "wordpress");
    await fs.access(extracted);
    await fs.cp(extracted, params.panelWebRoot, { recursive: true });
  } finally {
    await fs.rm(tmp, { recursive: true, force: true });
  }

  const wpConfig = buildWpConfigPhp({
    dbHost: params.dbHost,
    dbName: params.dbName,
    dbUser: params.dbUser,
    dbPassword: params.dbPassword,
    tablePrefix: "wp_",
  });

  await fs.writeFile(path.join(params.panelWebRoot, "wp-config.php"), wpConfig, "utf-8");
}
