import { randomBytes } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import net from "node:net";
import { docker } from "~/lib/docker.server";

function wpSalt(): string {
  return randomBytes(32).toString("base64url");
}

/**
 * Wait until MariaDB accepts TCP connections on the given host:port (Docker network).
 */
export async function waitForMysqlHost(
  host: string,
  port: number,
  opts: { timeoutMs?: number; intervalMs?: number } = {}
): Promise<void> {
  const timeoutMs = opts.timeoutMs ?? 120_000;
  const intervalMs = opts.intervalMs ?? 2_000;
  const deadline = Date.now() + timeoutMs;

  while (Date.now() < deadline) {
    const ok = await new Promise<boolean>((resolve) => {
      const socket = net.createConnection({ host, port }, () => {
        socket.end();
        resolve(true);
      });
      socket.on("error", () => resolve(false));
      socket.setTimeout(5_000, () => {
        socket.destroy();
        resolve(false);
      });
    });
    if (ok) return;
    await new Promise((r) => setTimeout(r, intervalMs));
  }

  throw new Error(
    `Timed out waiting for MySQL at ${host}:${port}. Check the database container logs.`
  );
}

function buildWpConfigPhp(params: {
  dbHost: string;
  dbName: string;
  dbUser: string;
  dbPassword: string;
  tablePrefix: string;
}): string {
  const keys = {
    AUTH_KEY: wpSalt(),
    SECURE_AUTH_KEY: wpSalt(),
    LOGGED_IN_KEY: wpSalt(),
    NONCE_KEY: wpSalt(),
    AUTH_SALT: wpSalt(),
    SECURE_AUTH_SALT: wpSalt(),
    LOGGED_IN_SALT: wpSalt(),
    NONCE_SALT: wpSalt(),
  };

  const keyLines = Object.entries(keys)
    .map(([k, v]) => `define('${k}', '${v.replace(/'/g, "\\'")}');`)
    .join("\n");

  return `<?php
/**
 * Generated by Jigsaw — https://github.com/03c/jigsaw
 */
define('DB_NAME', '${params.dbName.replace(/'/g, "\\'")}');
define('DB_USER', '${params.dbUser.replace(/'/g, "\\'")}');
define('DB_PASSWORD', '${params.dbPassword.replace(/'/g, "\\'")}');
define('DB_HOST', '${params.dbHost.replace(/'/g, "\\'")}');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');

${keyLines}

$table_prefix = '${params.tablePrefix.replace(/[^a-z0-9_]/gi, "") || "wp_"}';

define('WP_DEBUG', false);

if (!defined('ABSPATH')) {
    define('ABSPATH', __DIR__ . '/');
}

require_once ABSPATH . 'wp-settings.php';
`;
}

/**
 * Copy WordPress core from the published WordPress image into the site's web root on the Docker host.
 * Uses a one-shot container with dockerode (no `docker` CLI required inside the panel image).
 */
export async function copyWordPressCoreFromImage(params: {
  webImage: string;
  /** Absolute host path, e.g. /home/owner/site/public_html (same path the daemon bind-mounts) */
  hostWebRoot: string;
}): Promise<void> {
  await fs.mkdir(params.hostWebRoot, { recursive: true });

  const container = await docker.createContainer({
    Image: params.webImage,
    Cmd: ["sh", "-c", "cp -a /opt/jigsaw/wordpress-baked/. /out/"],
    HostConfig: {
      Binds: [`${params.hostWebRoot}:/out`],
      AutoRemove: true,
    },
  });

  await container.start();
  const wait = await container.wait();
  if (wait.StatusCode !== 0) {
    throw new Error(
      `WordPress core copy failed (exit ${wait.StatusCode}). Ensure image ${params.webImage} exists on this host.`
    );
  }
}

/**
 * Write wp-config.php after core files are on disk.
 */
export async function writeWordPressConfig(params: {
  panelWebRoot: string;
  dbHost: string;
  dbName: string;
  dbUser: string;
  dbPassword: string;
}): Promise<void> {
  const wpConfig = buildWpConfigPhp({
    dbHost: params.dbHost,
    dbName: params.dbName,
    dbUser: params.dbUser,
    dbPassword: params.dbPassword,
    tablePrefix: "wp_",
  });

  await fs.writeFile(path.join(params.panelWebRoot, "wp-config.php"), wpConfig, "utf-8");
}

/**
 * Ensure the customer web container can read wp-config.php (owned by panel uid on host).
 */
export async function chownWebRootForWebContainer(webContainerName: string): Promise<void> {
  try {
    const container = docker.getContainer(webContainerName);
    const exec = await container.exec({
      Cmd: ["chown", "-R", "www-data:www-data", "/var/www/html"],
      AttachStdout: true,
      AttachStderr: true,
      User: "root",
    });
    await new Promise<void>((resolve, reject) => {
      exec.start({ hijack: true, Tty: false }, (err, stream) => {
        if (err) {
          reject(err);
          return;
        }
        if (!stream) {
          resolve();
          return;
        }
        stream.on("end", () => resolve());
        stream.on("error", reject);
      });
    });
  } catch {
    // Best-effort; entrypoint also adjusts permissions on container start
  }
}
